spring.application.name=thinkhumble
server.port=5454

alpha.vantage.api.url=https://www.alphavantage.co/query
alpha.vantage.api.key=MGZOV0YU2MO1Z53O

# /api-docs endpoint custom path
springdoc.api-docs.path=/api-docs

# swagger-ui custom path
springdoc.swagger-ui.path=/swagger-ui.html

jwt.secret=ZWZkZGQ1NzY5ZjNlNjA1MjFlM2IxNzI0NzYyNzA0YjM3YzE5NjE1NTk4ZDk4ZGRjMzU3N2NlYTg3MWE0NDYxZA==
jwt.expiration=3600000 


spring.data.mongodb.uri=mongodb+srv://sutikshansikarwar:zxcvbnm0@cluster0.ybko8dp.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0

spring.data.mongodb.database=thinkhumble
